'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslations } from 'next-intl';
import { readPortalJson } from '@/lib/portal-fetch';

type Policy = { route_target_id: string; model_id: string; provider_id: string; provider_name: string; provider_model_name: string; upstream_protocol: string; upstream_operation: string | null; route_group: string | null; subject_fingerprint: string | null; subject_matches_current: boolean; retention_days: number | null; training_allowed: boolean; zdr_supported: boolean; evidence_url: string | null; verified_by: string | null; verified_at: string | null; expires_at: string | null; status: 'verified' | 'expired' | 'unknown'; effective_status: 'verified' | 'expired' | 'unknown'; invalidated_at: string | null; invalidation_reason: string | null; updated_at: string };
type Audit = { id: string; actor_id: string; created_at: string; snapshot: Record<string, unknown> };
type Draft = { retention: string; training: boolean; zdr: boolean; evidence: string; expiry: string; status: Policy['status'] };

function toLocalDate(value: string | null): string { return value ? new Date(value).toISOString().slice(0, 10) : ''; }
function defaultDraft(row: Policy): Draft { return { retention: row.retention_days == null ? '' : String(row.retention_days), training: row.training_allowed, zdr: row.zdr_supported, evidence: row.evidence_url ?? '', expiry: toLocalDate(row.expires_at), status: row.status }; }

export default function DataPolicyManager() {
	const t = useTranslations('dataPolicies');
	const [rows, setRows] = useState<Policy[]>([]);
	const [drafts, setDrafts] = useState<Record<string, Draft>>({});
	const [audits, setAudits] = useState<Record<string, Audit[]>>({});
	const [loading, setLoading] = useState(true);
	const [saving, setSaving] = useState<string | null>(null);
	const [message, setMessage] = useState<{ error: boolean; text: string } | null>(null);
	const load = useCallback(async () => {
		setLoading(true);
		try { const response = await fetch('/api/admin/data-policies', { cache: 'no-store' }); const payload = await readPortalJson<Policy[]>(response); if (!response.ok || !payload?.success) throw new Error(payload?.message ?? t('loadFailed')); const data = payload.data ?? []; setRows(data); setDrafts(Object.fromEntries(data.map((row) => [row.route_target_id, defaultDraft(row)]))); }
		catch (error) { setMessage({ error: true, text: error instanceof Error ? error.message : t('loadFailed') }); }
		finally { setLoading(false); }
	}, [t]);
	useEffect(() => { void load(); }, [load]);
	const summary = useMemo(() => ({ unknown: rows.filter((row) => row.effective_status === 'unknown').length, expired: rows.filter((row) => row.effective_status === 'expired').length, verified: rows.filter((row) => row.effective_status === 'verified').length, zdr: rows.filter((row) => row.effective_status === 'verified' && row.zdr_supported && row.retention_days === 0 && !row.training_allowed).length }), [rows]);
	const updateDraft = (id: string, patch: Partial<Draft>) => setDrafts((value) => ({ ...value, [id]: { ...value[id]!, ...patch } }));
	const save = async (row: Policy) => {
		const draft = drafts[row.route_target_id]; if (!draft) return; setSaving(row.route_target_id);
		try { const response = await fetch(`/api/admin/data-policies/${row.route_target_id}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ retention_days: draft.retention.trim() ? Number(draft.retention) : null, training_allowed: draft.training, zdr_supported: draft.zdr, evidence_url: draft.evidence || null, expires_at: draft.expiry ? new Date(`${draft.expiry}T23:59:59.999Z`).toISOString() : null, status: draft.status }) }); const payload = await readPortalJson(response); if (!response.ok || !payload?.success) throw new Error(payload?.message ?? t('saveFailed')); setMessage({ error: false, text: t('saved') }); await load(); }
		catch (error) { setMessage({ error: true, text: error instanceof Error ? error.message : t('saveFailed') }); }
		finally { setSaving(null); }
	};
	const showAudit = async (id: string) => { if (audits[id]) { setAudits((value) => { const next = { ...value }; delete next[id]; return next; }); return; } const response = await fetch(`/api/admin/data-policies/${id}/audit`, { cache: 'no-store' }); const payload = await readPortalJson<Audit[]>(response); if (!response.ok || !payload?.success) setMessage({ error: true, text: payload?.message ?? t('loadFailed') }); else setAudits((value) => ({ ...value, [id]: payload.data ?? [] })); };
	return <div className="space-y-6"><div><h1 className="text-2xl font-bold">{t('title')}</h1><p className="console-muted mt-1 text-sm">{t('subtitle')}</p></div>{message && <div className={`rounded-lg border p-3 text-sm ${message.error ? 'border-red-300 bg-red-50 text-red-700' : 'border-emerald-300 bg-emerald-50 text-emerald-700'}`}>{message.text}</div>}
		<div className="grid gap-3 sm:grid-cols-4">{(['verified','zdr','expired','unknown'] as const).map((key) => <div key={key} className="console-panel rounded-xl border p-4" style={{ borderColor: 'var(--console-border)' }}><p className="console-muted text-xs uppercase">{t(key)}</p><p className="mt-1 text-2xl font-semibold">{summary[key]}</p></div>)}</div>
		{loading ? <div className="console-muted py-12 text-center">{t('loading')}</div> : <div className="space-y-3">{rows.map((row) => { const draft = drafts[row.route_target_id] ?? defaultDraft(row); return <article key={row.route_target_id} className="console-panel rounded-xl border p-4" style={{ borderColor: 'var(--console-border)' }}><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{row.model_id}</h2><span className={`rounded-full border px-2 py-0.5 text-xs ${row.effective_status === 'verified' ? 'text-emerald-600' : row.effective_status === 'expired' ? 'text-amber-600' : 'text-red-600'}`}>{t(row.effective_status)}</span></div><p className="console-muted mt-1 text-xs">{row.provider_name} · {row.provider_model_name} · {row.upstream_protocol}/{row.upstream_operation ?? '*'}</p><code className="console-muted mt-1 block break-all text-[11px]">{row.route_target_id}</code>{row.invalidation_reason && <p className="mt-1 text-xs text-red-600">{t('invalidatedReason')}: <code>{row.invalidation_reason}</code></p>}</div><button className="self-start rounded-md border px-3 py-1.5 text-xs" onClick={() => void showAudit(row.route_target_id)}>{t('audit')}</button></div>
			<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><label className="text-xs">{t('status')}<select className="console-input mt-1 w-full rounded-md border px-2 py-2" value={draft.status} onChange={(e) => updateDraft(row.route_target_id, { status: e.target.value as Draft['status'] })}><option value="unknown">{t('unknown')}</option><option value="verified">{t('verified')}</option><option value="expired">{t('expired')}</option></select></label><label className="text-xs">{t('retention')}<input type="number" min="0" className="console-input mt-1 w-full rounded-md border px-2 py-2" value={draft.retention} onChange={(e) => updateDraft(row.route_target_id, { retention: e.target.value })} /></label><label className="text-xs">{t('expiry')}<input type="date" className="console-input mt-1 w-full rounded-md border px-2 py-2" value={draft.expiry} onChange={(e) => updateDraft(row.route_target_id, { expiry: e.target.value })} /></label><label className="flex items-end gap-2 pb-2 text-xs"><input type="checkbox" checked={draft.training} onChange={(e) => updateDraft(row.route_target_id, { training: e.target.checked })} />{t('training')}</label><label className="flex items-end gap-2 pb-2 text-xs"><input type="checkbox" checked={draft.zdr} onChange={(e) => updateDraft(row.route_target_id, { zdr: e.target.checked })} />{t('zdrSupported')}</label><button disabled={saving === row.route_target_id} className="self-end rounded-md bg-cyan-600 px-3 py-2 text-xs font-medium text-white disabled:opacity-50" onClick={() => void save(row)}>{saving === row.route_target_id ? t('saving') : t('save')}</button><label className="text-xs sm:col-span-2 lg:col-span-6">{t('evidence')}<input type="url" className="console-input mt-1 w-full rounded-md border px-2 py-2" value={draft.evidence} onChange={(e) => updateDraft(row.route_target_id, { evidence: e.target.value })} placeholder="https://..." /></label></div>
			{audits[row.route_target_id] && <div className="mt-4 border-t pt-3" style={{ borderColor: 'var(--console-border)' }}><h3 className="text-xs font-semibold">{t('auditHistory')}</h3><div className="mt-2 space-y-1">{audits[row.route_target_id]!.length === 0 ? <p className="console-muted text-xs">{t('noAudit')}</p> : audits[row.route_target_id]!.map((audit) => <div key={audit.id} className="rounded-md border px-3 py-2 text-xs"><span>{new Date(audit.created_at).toLocaleString()} · {audit.actor_id}</span><pre className="console-muted mt-1 overflow-auto text-[10px]">{JSON.stringify(audit.snapshot, null, 2)}</pre></div>)}</div></div>}
		</article>; })}</div>}
	</div>;
}
