export const ETL_TABLE_ORDER = [
	"users",
	"organizations",
	"organization_memberships",
	"workspaces",
	"workspace_memberships",
	"workspace_budgets",
	"identity_event_inbox",
	"api_keys",
	"management_api_keys",
	"byok_keys",
	"batches",
	"batch_items",
	"request_presets",
	"request_preset_versions",
	"guardrails",
	"guardrail_versions",
	"guardrail_assignments",
	"providers",
	"models",
	"model_tags",
	"model_endpoints",
	"route_pools",
	"model_surfaces",
	"model_routes",
	"model_endpoint_routes",
	"route_data_policies",
	"route_data_policy_audit",
	"route_pool_sticky_bindings",
	"api_key_request_logs",
	"provider_attempt_availability",
	"generation_feedback",
	"guardrail_budget_windows",
	"guardrail_budget_reservations",
	"user_budget_reservations",
	"public_model_daily_stats",
	"system_config",
	"user_audit_logs",
	"admin_api_keys",
	"shared_keys",
	"user_earnings",
	"shared_key_earnings",
	"withdrawals",
	"nft_mints",
	"portal_ledger_entries",
	"chain_job_transactions",
] as const;

export type EtlTableName = (typeof ETL_TABLE_ORDER)[number];

export const ETL_TABLES_TO_TRUNCATE = [...ETL_TABLE_ORDER].reverse();

export const TABLE_CONFLICT_KEYS: Record<EtlTableName, string[]> = {
	users: ["id"],
	organizations: ["id"],
	organization_memberships: ["organization_id", "subject"],
	workspaces: ["id"],
	workspace_memberships: ["id"],
	workspace_budgets: ["id"],
	identity_event_inbox: ["source", "event_id"],
	api_keys: ["id"],
	management_api_keys: ["id"],
	byok_keys: ["id"],
	batches: ["id"],
	batch_items: ["batch_id", "ordinal"],
	request_presets: ["id"],
	request_preset_versions: ["id"],
	guardrails: ["id"],
	guardrail_versions: ["id"],
	guardrail_assignments: ["id"],
	providers: ["id"],
	models: ["id"],
	model_tags: ["model_id", "tag"],
	model_endpoints: ["id"],
	route_pools: ["id"],
	model_surfaces: ["id"],
	model_routes: ["id"],
	model_endpoint_routes: ["endpoint_id", "route_target_id"],
	route_data_policies: ["route_target_id"],
	route_data_policy_audit: ["id"],
	route_pool_sticky_bindings: ["route_pool_id", "affinity_hash"],
	api_key_request_logs: ["id"],
	provider_attempt_availability: ["request_log_id", "attempt_index"],
	generation_feedback: ["id"],
	guardrail_budget_windows: [
		"workspace_id",
		"scope_type",
		"scope_id",
		"period",
		"period_start",
	],
	guardrail_budget_reservations: ["id"],
	user_budget_reservations: ["request_id"],
	public_model_daily_stats: ["stat_date", "model_id", "shard"],
	system_config: ["key"],
	user_audit_logs: ["id"],
	admin_api_keys: ["id"],
	shared_keys: ["id"],
	user_earnings: ["user_id"],
	shared_key_earnings: ["id"],
	withdrawals: ["id"],
	nft_mints: ["id"],
	portal_ledger_entries: ["id"],
	chain_job_transactions: ["job_kind", "job_id"],
};

/**
 * Sessions intentionally do not cross the database boundary. A cutover must
 * force both users and administrators to authenticate against the new primary.
 */
export const ETL_EXCLUDED_SESSION_TABLES = [
	"portal_sessions",
	"admin_sessions",
] as const;

/** SQLite persists booleans as 0/1 while PostgreSQL requires true/false. */
export const TABLE_BOOLEAN_COLUMNS: Partial<
	Record<EtlTableName, readonly string[]>
> = {
	api_keys: ["include_byok_in_limit"],
	byok_keys: [
		"disabled",
		"is_fallback",
		"always_use_for_provider",
		"always_use_for_matching_models",
	],
	workspaces: ["is_default"],
	model_endpoints: ["supports_implicit_caching", "supports_voice_cloning"],
	route_pools: ["sticky_enabled"],
	route_data_policies: ["training_allowed", "zdr_supported"],
};
