-- REVIEW ONLY. Install after the v2 economic producer, before any v2 event.
-- The ordinary-user account receipt is generated by database triggers, not by
-- a caller-supplied value. No formal migration or production activation here.
-- Apply as the dedicated migrator LOGIN in one transaction with:
--   SET LOCAL cinatoken.shared_key_buyer_budget_receipt_activation = 'reviewed-v1';
SET LOCAL lock_timeout = '2s';
SET LOCAL statement_timeout = '15s';
SET LOCAL search_path TO pg_catalog, pg_temp;
LOCK TABLE cinatoken_gateway.schema_migrations,
  cinatoken_gateway.users,
  cinatoken_gateway.user_budget_reservations,
  cinatoken_economic_outbox.shared_key_economic_events,
  cinatoken_economic_outbox.shared_key_economic_producer_tx_markers
  IN SHARE ROW EXCLUSIVE MODE;

DO $preflight$
DECLARE migrator_oid oid;
DECLARE runtime_oid oid;
BEGIN
  SELECT oid INTO migrator_oid FROM pg_catalog.pg_roles
    WHERE rolname='cinatoken_gateway_migrator';
  SELECT oid INTO runtime_oid FROM pg_catalog.pg_roles
    WHERE rolname='cinatoken_gateway_runtime';
  IF pg_catalog.current_setting(
      'cinatoken.shared_key_buyer_budget_receipt_activation',true)
        IS DISTINCT FROM 'reviewed-v1'
    OR CURRENT_USER<>'cinatoken_gateway_migrator'
    OR SESSION_USER<>CURRENT_USER
    OR migrator_oid IS NULL OR runtime_oid IS NULL
    OR (SELECT pg_catalog.count(*) FROM cinatoken_gateway.schema_migrations)<>73
    OR (SELECT pg_catalog.md5(pg_catalog.string_agg(version,E'\n'
        ORDER BY version COLLATE "C")) FROM cinatoken_gateway.schema_migrations)
      <>'ca1ea96a1b4bcd0675642f30dcf48042'
    OR EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE oid=runtime_oid
      AND (rolsuper OR rolreplication OR rolbypassrls))
    OR pg_catalog.pg_has_role(runtime_oid,migrator_oid,'MEMBER')
    OR pg_catalog.to_regclass(
      'cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts') IS NOT NULL
    OR pg_catalog.to_regclass(
      'cinatoken_economic_outbox.shared_key_buyer_reservation_admissions') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.capture_buyer_budget_tx_receipt()') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.verify_buyer_budget_tx_receipt()') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.capture_buyer_reservation_admission()') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.verify_buyer_reservation_admission()') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.recheck_buyer_budget_tx_after_account_change(text)') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.guard_buyer_reservation_admission_mutation()') IS NOT NULL
    OR pg_catalog.to_regprocedure(
      'cinatoken_economic_outbox.write_shared_key_economic_event_v2(text,text,text,bigint,jsonb,text)') IS NULL
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint
      WHERE conrelid='cinatoken_economic_outbox.shared_key_economic_events'::pg_catalog.regclass
        AND conname='shared_key_economic_event_version_debit'
        AND contype='c' AND convalidated)
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger
      WHERE tgrelid='cinatoken_economic_outbox.shared_key_economic_events'::pg_catalog.regclass
        AND tgname='shared_key_economic_events_verify_buyer_debit_v2'
        AND tgenabled='O' AND tgdeferrable AND tginitdeferred
        AND tgfoid='cinatoken_economic_outbox.verify_buyer_debit_v2()'::pg_catalog.regprocedure)
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger
      WHERE tgrelid='cinatoken_gateway.api_key_request_logs'::pg_catalog.regclass
        AND tgname='api_key_request_logs_mark_shared_key_economic_tx'
        AND tgenabled='O'
        AND tgfoid='cinatoken_economic_outbox.mark_shared_key_buyer_log_tx()'::pg_catalog.regprocedure)
    OR EXISTS (SELECT 1 FROM pg_catalog.pg_class c
      WHERE c.oid IN ('cinatoken_gateway.users'::pg_catalog.regclass,
          'cinatoken_gateway.user_budget_reservations'::pg_catalog.regclass,
          'cinatoken_economic_outbox.shared_key_economic_events'::pg_catalog.regclass,
          'cinatoken_economic_outbox.shared_key_economic_producer_tx_markers'::pg_catalog.regclass)
        AND (c.relowner<>migrator_oid OR c.relkind<>'r'
          OR c.relrowsecurity OR c.relforcerowsecurity))
    OR pg_catalog.has_table_privilege(runtime_oid,
      'cinatoken_economic_outbox.shared_key_economic_events'::pg_catalog.regclass,'INSERT')
    OR pg_catalog.has_table_privilege(runtime_oid,
      'cinatoken_economic_outbox.shared_key_economic_producer_tx_markers'::pg_catalog.regclass,'INSERT')
    OR pg_catalog.has_table_privilege(runtime_oid,
      'cinatoken_economic_outbox.shared_key_economic_producer_tx_markers'::pg_catalog.regclass,'UPDATE')
    OR pg_catalog.has_table_privilege(runtime_oid,
      'cinatoken_gateway.user_budget_reservations'::pg_catalog.regclass,'TRUNCATE')
    OR (SELECT pg_catalog.count(*) FROM pg_catalog.pg_proc p
      JOIN pg_catalog.pg_language l ON l.oid=p.prolang
      WHERE p.oid IN (
        'cinatoken_economic_outbox.mark_shared_key_buyer_log_tx()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.verify_buyer_debit_v2()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.capture_v2_reservation_settlement()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.guard_v2_reservation_mutation()'::pg_catalog.regprocedure)
        AND p.proowner=migrator_oid AND l.lanname='plpgsql'
        AND p.prosecdef AND p.provolatile='v'
        AND p.proconfig=ARRAY['search_path=pg_catalog, pg_temp']::text[]
        AND pg_catalog.md5(pg_catalog.replace(p.prosrc,
          pg_catalog.chr(13)||pg_catalog.chr(10),pg_catalog.chr(10)))=
          CASE p.proname
            WHEN 'mark_shared_key_buyer_log_tx' THEN '371e7930db542a724cf0385fbf6a1183'
            WHEN 'verify_buyer_debit_v2' THEN 'f58977880d4f575264a2eb7110902b2b'
            WHEN 'capture_v2_reservation_settlement' THEN '2b596a5e1d55db62c68b74e3b3296e96'
            WHEN 'guard_v2_reservation_mutation' THEN 'ea9c363cfbb832a9f414ada3cee1a6cb'
            ELSE '' END)<>4
    OR EXISTS (SELECT 1 FROM pg_catalog.pg_default_acl d,
        LATERAL pg_catalog.aclexplode(d.defaclacl) acl
      WHERE d.defaclrole=migrator_oid
        AND (d.defaclnamespace=0 OR
          d.defaclnamespace='cinatoken_economic_outbox'::pg_catalog.regnamespace)
        AND d.defaclobjtype IN ('f','r') AND acl.grantee<>migrator_oid)
  THEN
    RAISE EXCEPTION 'Buyer budget receipt activation or dependency differs';
  END IF;
END;
$preflight$;

-- This is a transaction-local accounting witness retained for audit. The
-- receipt is keyed by the full xid8; the runtime cannot write or read it.
-- Lifecycle/epoch changes poison that user's entire transaction receipt.
CREATE TABLE cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts (
  xact_id xid8 NOT NULL,
  user_id text NOT NULL,
  budget_epoch bigint NOT NULL,
  spent_delta_micros numeric NOT NULL DEFAULT 0,
  reserved_delta_micros numeric NOT NULL DEFAULT 0,
  lifecycle_changed boolean NOT NULL DEFAULT false,
  PRIMARY KEY (xact_id,user_id)
);

-- A deferred constraint may be switched to IMMEDIATE by its caller. Recheck
-- previously validated events and admissions on every later account mutation;
-- the final account state cannot invalidate a validation that ran early.
CREATE FUNCTION cinatoken_economic_outbox.recheck_buyer_budget_tx_after_account_change(
  p_user_id text)
RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path TO pg_catalog, pg_temp AS $recheck$
DECLARE account record;
DECLARE receipt record;
DECLARE needed_spent numeric;
DECLARE needed_release numeric;
DECLARE event_count bigint;
DECLARE required_hold numeric;
BEGIN
  SELECT budget_epoch,spent_delta_micros,reserved_delta_micros,
      lifecycle_changed INTO receipt
    FROM cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts
    WHERE xact_id=pg_catalog.pg_current_xact_id() AND user_id=p_user_id;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT id,budget_epoch,budget_max,budget_spent,budget_reserved_micros
    INTO account FROM cinatoken_gateway.users WHERE id=p_user_id;
  SELECT pg_catalog.count(*),
      COALESCE(pg_catalog.sum(e.buyer_debit_micros),0)::numeric,
      COALESCE(pg_catalog.sum(r.reserved_micros) FILTER
        (WHERE r.request_id IS NOT NULL),0)::numeric
    INTO event_count,needed_spent,needed_release
    FROM cinatoken_economic_outbox.shared_key_economic_events e
    JOIN cinatoken_economic_outbox.shared_key_economic_producer_tx_markers m
      ON m.request_log_id=e.request_log_id
    LEFT JOIN cinatoken_gateway.user_budget_reservations r
      ON r.request_id=e.request_log_id
    WHERE m.log_xact_id=pg_catalog.pg_current_xact_id()
      AND e.event_version=2 AND e.buyer_user_id=p_user_id;
  IF event_count>0 AND (account.id IS NULL
      OR receipt.lifecycle_changed IS NOT FALSE
      OR receipt.budget_epoch IS DISTINCT FROM account.budget_epoch
      OR receipt.spent_delta_micros<needed_spent
      OR receipt.reserved_delta_micros>-needed_release) THEN
    RAISE EXCEPTION 'Later account mutation invalidates buyer economic receipt'
      USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_later_change';
  END IF;
  IF EXISTS (SELECT 1 FROM
      cinatoken_economic_outbox.shared_key_buyer_reservation_admissions a
      WHERE a.admission_xact_id=pg_catalog.pg_current_xact_id()
        AND a.user_id=p_user_id AND a.hold_verified) THEN
    SELECT COALESCE(pg_catalog.sum(a.reserved_micros),0)::numeric
      INTO required_hold FROM
      cinatoken_economic_outbox.shared_key_buyer_reservation_admissions a
      WHERE a.admission_xact_id=pg_catalog.pg_current_xact_id()
        AND a.user_id=p_user_id AND a.budget_epoch=receipt.budget_epoch;
    IF account.id IS NULL OR receipt.lifecycle_changed IS NOT FALSE
      OR account.budget_epoch IS DISTINCT FROM receipt.budget_epoch
      OR account.budget_max IS NULL
      OR receipt.reserved_delta_micros<required_hold
      OR EXISTS (SELECT 1 FROM
          cinatoken_economic_outbox.shared_key_buyer_reservation_admissions a
          JOIN cinatoken_gateway.user_budget_reservations r
            ON r.request_id=a.request_id
          WHERE a.admission_xact_id=pg_catalog.pg_current_xact_id()
            AND a.user_id=p_user_id AND a.hold_verified
            AND (r.limit_micros IS DISTINCT FROM LEAST(
                ROUND(GREATEST(account.budget_max,0::numeric)*1000000::numeric),
                9007199254740991::numeric)
              OR LEAST(ROUND(GREATEST(account.budget_spent,0::numeric)
                  *1000000::numeric),9007199254740991::numeric)
                +account.budget_reserved_micros>r.limit_micros)) THEN
      RAISE EXCEPTION 'Later account mutation invalidates buyer admission'
        USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_admission_later_change';
    END IF;
  END IF;
END;
$recheck$;

CREATE FUNCTION cinatoken_economic_outbox.capture_buyer_budget_tx_receipt()
RETURNS trigger LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path TO pg_catalog, pg_temp AS $capture$
DECLARE receipt_user text;
DECLARE receipt_epoch bigint;
DECLARE spent_delta numeric := 0;
DECLARE reserved_delta numeric := 0;
DECLARE changed boolean := false;
BEGIN
  IF TG_RELID<>'cinatoken_gateway.users'::pg_catalog.regclass
    OR TG_NAME<>'users_capture_shared_key_buyer_budget_tx'
    OR TG_LEVEL<>'ROW' OR TG_OP NOT IN ('INSERT','UPDATE','DELETE') THEN
    RAISE EXCEPTION 'Buyer budget receipt trigger binding differs';
  END IF;
  IF TG_OP='UPDATE' THEN
    receipt_user:=OLD.id;
    receipt_epoch:=OLD.budget_epoch;
    changed:=OLD.id IS DISTINCT FROM NEW.id
      OR OLD.budget_epoch IS DISTINCT FROM NEW.budget_epoch;
    spent_delta:=(NEW.budget_spent-OLD.budget_spent)*1000000::numeric;
    reserved_delta:=NEW.budget_reserved_micros-OLD.budget_reserved_micros;
    IF NOT changed AND spent_delta=0 AND reserved_delta=0
      AND OLD.budget_max IS NOT DISTINCT FROM NEW.budget_max THEN
      RETURN NULL;
    END IF;
  ELSIF TG_OP='INSERT' THEN
    receipt_user:=NEW.id;
    receipt_epoch:=NEW.budget_epoch;
    changed:=true;
  ELSE
    receipt_user:=OLD.id;
    receipt_epoch:=OLD.budget_epoch;
    changed:=true;
  END IF;
  INSERT INTO cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts AS r
    (xact_id,user_id,budget_epoch,spent_delta_micros,
      reserved_delta_micros,lifecycle_changed)
    VALUES (pg_catalog.pg_current_xact_id(),receipt_user,receipt_epoch,
      spent_delta,reserved_delta,changed)
    ON CONFLICT (xact_id,user_id) DO UPDATE SET
      spent_delta_micros=r.spent_delta_micros+EXCLUDED.spent_delta_micros,
      reserved_delta_micros=r.reserved_delta_micros+EXCLUDED.reserved_delta_micros,
      lifecycle_changed=r.lifecycle_changed OR EXCLUDED.lifecycle_changed
        OR r.budget_epoch IS DISTINCT FROM EXCLUDED.budget_epoch;
  IF TG_OP='UPDATE' AND OLD.id IS DISTINCT FROM NEW.id THEN
    INSERT INTO cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts AS r
      (xact_id,user_id,budget_epoch,lifecycle_changed)
      VALUES (pg_catalog.pg_current_xact_id(),NEW.id,NEW.budget_epoch,true)
      ON CONFLICT (xact_id,user_id) DO UPDATE SET lifecycle_changed=true;
  END IF;
  PERFORM cinatoken_economic_outbox.recheck_buyer_budget_tx_after_account_change(
    receipt_user);
  IF TG_OP='UPDATE' AND OLD.id IS DISTINCT FROM NEW.id THEN
    PERFORM cinatoken_economic_outbox.recheck_buyer_budget_tx_after_account_change(
      NEW.id);
  END IF;
  RETURN NULL;
END;
$capture$;
CREATE TRIGGER users_capture_shared_key_buyer_budget_tx
  AFTER INSERT OR UPDATE OR DELETE ON cinatoken_gateway.users
  FOR EACH ROW EXECUTE FUNCTION
    cinatoken_economic_outbox.capture_buyer_budget_tx_receipt();

-- A reservation must have occupied buyer capacity before it can support a
-- current-epoch v2 debit. An old-epoch hold alone is not a spend receipt.
-- Capture a candidate for every reservation, but do not change the behavior
-- of legacy, unlimited-budget or recovery writers: a candidate becomes a
-- v2-eligible admission only after the deferred account-hold check succeeds.
CREATE TABLE cinatoken_economic_outbox.shared_key_buyer_reservation_admissions (
  request_id text PRIMARY KEY REFERENCES
    cinatoken_gateway.user_budget_reservations(request_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  user_id text NOT NULL,
  api_key_id text NOT NULL,
  budget_epoch bigint NOT NULL,
  reserved_micros bigint NOT NULL CHECK (reserved_micros>0),
  admission_xact_id xid8 NOT NULL,
  hold_verified boolean NOT NULL DEFAULT false
);
CREATE INDEX shared_key_buyer_reservation_admissions_tx
  ON cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
    (admission_xact_id,user_id,budget_epoch);

CREATE FUNCTION cinatoken_economic_outbox.capture_buyer_reservation_admission()
RETURNS trigger LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path TO pg_catalog, pg_temp AS $capture$
BEGIN
  IF TG_RELID<>'cinatoken_gateway.user_budget_reservations'::pg_catalog.regclass
    OR TG_NAME<>'user_budget_reservations_capture_shared_key_admission'
    OR TG_LEVEL<>'ROW' OR TG_OP<>'INSERT' THEN
    RAISE EXCEPTION 'Buyer reservation admission trigger binding differs';
  END IF;
  INSERT INTO cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
    (request_id,user_id,api_key_id,budget_epoch,reserved_micros,
      admission_xact_id)
    VALUES (NEW.request_id,NEW.user_id,NEW.api_key_id,NEW.budget_epoch,
      NEW.reserved_micros,pg_catalog.pg_current_xact_id());
  RETURN NULL;
END;
$capture$;
CREATE TRIGGER user_budget_reservations_capture_shared_key_admission
  AFTER INSERT ON cinatoken_gateway.user_budget_reservations
  FOR EACH ROW EXECUTE FUNCTION
    cinatoken_economic_outbox.capture_buyer_reservation_admission();

-- A caller can execute a deferred admission or event check before its last
-- statement. The account trigger covers later account changes; this immediate
-- guard keeps the reservation identity, epoch, limit and hold evidence stable.
CREATE FUNCTION cinatoken_economic_outbox.guard_buyer_reservation_admission_mutation()
RETURNS trigger LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path TO pg_catalog, pg_temp AS $guard$
DECLARE protected boolean;
BEGIN
  IF TG_RELID<>'cinatoken_gateway.user_budget_reservations'::pg_catalog.regclass
    OR TG_NAME<>'user_budget_reservations_guard_shared_key_admission'
    OR TG_LEVEL<>'ROW' OR TG_OP NOT IN ('UPDATE','DELETE') THEN
    RAISE EXCEPTION 'Buyer reservation admission mutation guard binding differs';
  END IF;
  SELECT EXISTS (SELECT 1 FROM
      cinatoken_economic_outbox.shared_key_buyer_reservation_admissions a
      WHERE a.request_id=OLD.request_id AND a.hold_verified)
    OR EXISTS (SELECT 1 FROM
      cinatoken_economic_outbox.shared_key_economic_events e
      WHERE e.request_log_id=OLD.request_id AND e.event_version=2)
    INTO protected;
  IF TG_OP='DELETE' THEN
    IF protected THEN
      RAISE EXCEPTION 'Verified buyer admission cannot be deleted'
        USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_admission_immutable';
    END IF;
    RETURN OLD;
  END IF;
  IF protected AND (OLD.request_id IS DISTINCT FROM NEW.request_id
    OR OLD.user_id IS DISTINCT FROM NEW.user_id
    OR OLD.api_key_id IS DISTINCT FROM NEW.api_key_id
    OR OLD.budget_epoch IS DISTINCT FROM NEW.budget_epoch
    OR OLD.limit_micros IS DISTINCT FROM NEW.limit_micros
    OR OLD.reserved_micros IS DISTINCT FROM NEW.reserved_micros) THEN
    RAISE EXCEPTION 'Verified buyer admission cannot change financial identity or capacity'
      USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_admission_immutable';
  END IF;
  RETURN NEW;
END;
$guard$;
CREATE TRIGGER user_budget_reservations_guard_shared_key_admission
  BEFORE UPDATE OR DELETE ON cinatoken_gateway.user_budget_reservations
  FOR EACH ROW EXECUTE FUNCTION
    cinatoken_economic_outbox.guard_buyer_reservation_admission_mutation();

CREATE FUNCTION cinatoken_economic_outbox.verify_buyer_reservation_admission()
RETURNS trigger LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path TO pg_catalog, pg_temp AS $verify$
DECLARE account record;
DECLARE reservation record;
DECLARE receipt record;
DECLARE required_micros numeric;
BEGIN
  IF TG_RELID<>'cinatoken_economic_outbox.shared_key_buyer_reservation_admissions'::pg_catalog.regclass
    OR TG_NAME<>'shared_key_buyer_reservation_admissions_verify'
    OR TG_LEVEL<>'ROW' OR TG_OP<>'INSERT' THEN
    RAISE EXCEPTION 'Buyer reservation admission verifier binding differs';
  END IF;
  -- Other reservation writers keep their original transaction behavior. A
  -- non-READ-COMMITTED candidate simply cannot back a v2 economic event.
  IF pg_catalog.current_setting('transaction_isolation')<>'read committed' THEN
    RETURN NULL;
  END IF;
  IF NEW.admission_xact_id<>pg_catalog.pg_current_xact_id() THEN
    RAISE EXCEPTION 'Buyer reservation admission requires same READ COMMITTED transaction'
      USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_admission_protocol';
  END IF;
  SELECT budget_epoch,reserved_delta_micros,lifecycle_changed INTO receipt
    FROM cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts
    WHERE xact_id=NEW.admission_xact_id AND user_id=NEW.user_id;
  IF NOT FOUND OR receipt.lifecycle_changed IS NOT FALSE
    OR receipt.budget_epoch IS DISTINCT FROM NEW.budget_epoch
    OR receipt.reserved_delta_micros<=0 THEN RETURN NULL; END IF;
  SELECT id,budget_epoch,budget_max,budget_spent,budget_reserved_micros INTO account
    FROM cinatoken_gateway.users WHERE id=NEW.user_id FOR SHARE;
  SELECT user_id,api_key_id,budget_epoch,limit_micros,reserved_micros,
      state,settled_micros
    INTO reservation FROM cinatoken_gateway.user_budget_reservations
    WHERE request_id=NEW.request_id;
  SELECT pg_catalog.sum(reserved_micros)::numeric INTO required_micros
    FROM cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
    WHERE admission_xact_id=NEW.admission_xact_id
      AND user_id=NEW.user_id AND budget_epoch=NEW.budget_epoch;
  IF account.id IS NOT NULL AND account.budget_epoch=NEW.budget_epoch
    AND account.budget_max IS NOT NULL
    AND reservation.limit_micros=LEAST(
      ROUND(GREATEST(account.budget_max,0::numeric)*1000000::numeric),
      9007199254740991::numeric)
    AND LEAST(ROUND(GREATEST(account.budget_spent,0::numeric)
      *1000000::numeric),9007199254740991::numeric)
      +account.budget_reserved_micros<=reservation.limit_micros
    AND reservation.user_id IS NOT DISTINCT FROM NEW.user_id
    AND reservation.api_key_id IS NOT DISTINCT FROM NEW.api_key_id
    AND reservation.budget_epoch IS NOT DISTINCT FROM NEW.budget_epoch
    AND reservation.reserved_micros IS NOT DISTINCT FROM NEW.reserved_micros
    AND reservation.state IN ('reserved','dispatched')
    AND reservation.settled_micros=0
    AND receipt.budget_epoch IS NOT DISTINCT FROM NEW.budget_epoch
    AND receipt.lifecycle_changed IS FALSE
    AND receipt.reserved_delta_micros>=required_micros THEN
    UPDATE cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
      SET hold_verified=true WHERE request_id=NEW.request_id
        AND admission_xact_id=NEW.admission_xact_id;
  END IF;
  RETURN NULL;
END;
$verify$;
CREATE CONSTRAINT TRIGGER shared_key_buyer_reservation_admissions_verify
  AFTER INSERT ON cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION
    cinatoken_economic_outbox.verify_buyer_reservation_admission();

-- At COMMIT, one user's complete v2 batch must fit the final net account
-- increase and, for reservations, the released hold. The old-epoch branch is
-- blocked until a separate settlement or adjustment ledger can prove its
-- debit. v1 and no-charge events retain their prior rules.
CREATE FUNCTION cinatoken_economic_outbox.verify_buyer_budget_tx_receipt()
RETURNS trigger LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path TO pg_catalog, pg_temp AS $verify$
DECLARE account record;
DECLARE reservation record;
DECLARE admission record;
DECLARE receipt record;
DECLARE needed_spent numeric;
DECLARE needed_release numeric;
BEGIN
  IF TG_RELID<>'cinatoken_economic_outbox.shared_key_economic_events'::pg_catalog.regclass
    OR TG_NAME<>'shared_key_economic_events_verify_buyer_budget_tx'
    OR TG_LEVEL<>'ROW' OR TG_OP<>'INSERT' THEN
    RAISE EXCEPTION 'Buyer budget receipt verifier binding differs';
  END IF;
  IF NEW.event_version=1 THEN RETURN NULL; END IF;
  IF NEW.event_version<>2
    OR pg_catalog.current_setting('transaction_isolation')<>'read committed'
    OR NOT EXISTS (SELECT 1 FROM
        cinatoken_economic_outbox.shared_key_economic_producer_tx_markers m
      WHERE m.request_log_id=NEW.request_log_id
        AND m.log_xact_id=pg_catalog.pg_current_xact_id()) THEN
    RAISE EXCEPTION 'Buyer budget receipt requires same buyer-log transaction'
      USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_protocol';
  END IF;
  SELECT user_id,api_key_id,budget_epoch,reserved_micros
    INTO reservation FROM cinatoken_gateway.user_budget_reservations
    WHERE request_id=NEW.request_log_id;
  SELECT id,budget_epoch INTO account FROM cinatoken_gateway.users
    WHERE id=NEW.buyer_user_id FOR SHARE;
  SELECT budget_epoch,spent_delta_micros,reserved_delta_micros,
      lifecycle_changed INTO receipt
    FROM cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts
    WHERE xact_id=pg_catalog.pg_current_xact_id()
      AND user_id=NEW.buyer_user_id;
  IF account.id IS NULL OR receipt.lifecycle_changed IS TRUE
    OR (receipt.budget_epoch IS NOT NULL
      AND receipt.budget_epoch<>account.budget_epoch) THEN
    RAISE EXCEPTION 'Buyer account identity or epoch changed in event transaction'
      USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_epoch';
  END IF;
  IF reservation.user_id IS NOT NULL THEN
    IF reservation.user_id IS DISTINCT FROM NEW.buyer_user_id
      OR reservation.api_key_id IS DISTINCT FROM NEW.buyer_api_key_id THEN
      RAISE EXCEPTION 'Buyer reservation identity differs from account receipt'
        USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_identity';
    END IF;
    SELECT user_id,api_key_id,budget_epoch,reserved_micros,hold_verified
      INTO admission FROM
      cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
      WHERE request_id=NEW.request_log_id;
    IF admission.hold_verified IS DISTINCT FROM true
      OR admission.user_id IS DISTINCT FROM reservation.user_id
      OR admission.api_key_id IS DISTINCT FROM reservation.api_key_id
      OR admission.budget_epoch IS DISTINCT FROM reservation.budget_epoch
      OR admission.reserved_micros IS DISTINCT FROM reservation.reserved_micros THEN
      RAISE EXCEPTION 'Buyer debit lacks proven reservation admission'
        USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_admission';
    END IF;
    IF reservation.budget_epoch IS DISTINCT FROM account.budget_epoch THEN
      RAISE EXCEPTION 'Old-epoch reservation hold is not a buyer spend receipt'
        USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_old_epoch';
    END IF;
  END IF;
  SELECT COALESCE(pg_catalog.sum(e.buyer_debit_micros),0)::numeric,
    COALESCE(pg_catalog.sum(r.reserved_micros) FILTER
      (WHERE r.request_id IS NOT NULL),0)::numeric
    INTO needed_spent,needed_release
    FROM cinatoken_economic_outbox.shared_key_economic_events e
    JOIN cinatoken_economic_outbox.shared_key_economic_producer_tx_markers m
      ON m.request_log_id=e.request_log_id
    LEFT JOIN cinatoken_gateway.user_budget_reservations r
      ON r.request_id=e.request_log_id
    WHERE m.log_xact_id=pg_catalog.pg_current_xact_id()
      AND e.event_version=2 AND e.buyer_user_id=NEW.buyer_user_id;
  IF COALESCE(receipt.spent_delta_micros,0)<needed_spent
    OR COALESCE(receipt.reserved_delta_micros,0)>-needed_release THEN
    RAISE EXCEPTION 'Buyer debit lacks same-transaction net account charge or hold release'
      USING ERRCODE='23514',CONSTRAINT='shared_key_buyer_receipt_net_debit';
  END IF;
  RETURN NULL;
END;
$verify$;
CREATE CONSTRAINT TRIGGER shared_key_economic_events_verify_buyer_budget_tx
  AFTER INSERT ON cinatoken_economic_outbox.shared_key_economic_events
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION
    cinatoken_economic_outbox.verify_buyer_budget_tx_receipt();

REVOKE ALL ON TABLE
  cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts,
  cinatoken_economic_outbox.shared_key_buyer_reservation_admissions
  FROM PUBLIC,cinatoken_gateway_runtime;
REVOKE ALL ON FUNCTION
  cinatoken_economic_outbox.recheck_buyer_budget_tx_after_account_change(text),
  cinatoken_economic_outbox.capture_buyer_budget_tx_receipt(),
  cinatoken_economic_outbox.verify_buyer_budget_tx_receipt(),
  cinatoken_economic_outbox.capture_buyer_reservation_admission(),
  cinatoken_economic_outbox.guard_buyer_reservation_admission_mutation(),
  cinatoken_economic_outbox.verify_buyer_reservation_admission()
  FROM PUBLIC,cinatoken_gateway_runtime;

DO $postflight$
DECLARE migrator_oid oid;
DECLARE runtime_oid oid;
BEGIN
  SELECT oid INTO migrator_oid FROM pg_catalog.pg_roles
    WHERE rolname='cinatoken_gateway_migrator';
  SELECT oid INTO runtime_oid FROM pg_catalog.pg_roles
    WHERE rolname='cinatoken_gateway_runtime';
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_class c,
      LATERAL pg_catalog.aclexplode(COALESCE(c.relacl,
        pg_catalog.acldefault('r',c.relowner))) acl
      WHERE c.oid IN (
        'cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts'::pg_catalog.regclass,
        'cinatoken_economic_outbox.shared_key_buyer_reservation_admissions'::pg_catalog.regclass)
        AND (c.relowner<>migrator_oid OR acl.grantee<>migrator_oid))
    OR EXISTS (SELECT 1 FROM pg_catalog.pg_attribute a,
        LATERAL pg_catalog.aclexplode(a.attacl) acl
      WHERE a.attrelid IN (
        'cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts'::pg_catalog.regclass,
        'cinatoken_economic_outbox.shared_key_buyer_reservation_admissions'::pg_catalog.regclass)
        AND NOT a.attisdropped AND acl.grantee<>migrator_oid)
    OR EXISTS (SELECT 1 FROM pg_catalog.pg_proc p,
      LATERAL pg_catalog.aclexplode(COALESCE(p.proacl,
        pg_catalog.acldefault('f',p.proowner))) acl
      WHERE p.oid IN (
        'cinatoken_economic_outbox.capture_buyer_budget_tx_receipt()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.recheck_buyer_budget_tx_after_account_change(text)'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.verify_buyer_budget_tx_receipt()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.capture_buyer_reservation_admission()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.guard_buyer_reservation_admission_mutation()'::pg_catalog.regprocedure,
        'cinatoken_economic_outbox.verify_buyer_reservation_admission()'::pg_catalog.regprocedure)
        AND (p.proowner<>migrator_oid OR NOT p.prosecdef
          OR p.provolatile<>'v' OR p.proconfig<>ARRAY[
            'search_path=pg_catalog, pg_temp']::text[]
          OR acl.grantee<>migrator_oid))
    OR pg_catalog.has_table_privilege(runtime_oid,
      'cinatoken_economic_outbox.shared_key_buyer_budget_tx_receipts'::pg_catalog.regclass,'SELECT')
    OR pg_catalog.has_table_privilege(runtime_oid,
      'cinatoken_economic_outbox.shared_key_buyer_reservation_admissions'::pg_catalog.regclass,'INSERT')
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger WHERE
      tgrelid='cinatoken_gateway.users'::pg_catalog.regclass
      AND tgname='users_capture_shared_key_buyer_budget_tx' AND tgenabled='O'
      AND NOT tgdeferrable AND tgfoid=
        'cinatoken_economic_outbox.capture_buyer_budget_tx_receipt()'::pg_catalog.regprocedure)
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger WHERE
      tgrelid='cinatoken_gateway.user_budget_reservations'::pg_catalog.regclass
      AND tgname='user_budget_reservations_capture_shared_key_admission'
      AND tgenabled='O' AND NOT tgdeferrable AND tgfoid=
        'cinatoken_economic_outbox.capture_buyer_reservation_admission()'::pg_catalog.regprocedure)
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger WHERE
      tgrelid='cinatoken_gateway.user_budget_reservations'::pg_catalog.regclass
      AND tgname='user_budget_reservations_guard_shared_key_admission'
      AND tgenabled='O' AND NOT tgdeferrable AND tgfoid=
        'cinatoken_economic_outbox.guard_buyer_reservation_admission_mutation()'::pg_catalog.regprocedure)
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger WHERE
      tgrelid='cinatoken_economic_outbox.shared_key_buyer_reservation_admissions'::pg_catalog.regclass
      AND tgname='shared_key_buyer_reservation_admissions_verify'
      AND tgenabled='O' AND tgdeferrable AND tginitdeferred AND tgfoid=
        'cinatoken_economic_outbox.verify_buyer_reservation_admission()'::pg_catalog.regprocedure)
    OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_trigger WHERE
      tgrelid='cinatoken_economic_outbox.shared_key_economic_events'::pg_catalog.regclass
      AND tgname='shared_key_economic_events_verify_buyer_budget_tx'
      AND tgenabled='O' AND tgdeferrable AND tginitdeferred AND tgfoid=
        'cinatoken_economic_outbox.verify_buyer_budget_tx_receipt()'::pg_catalog.regprocedure)
  THEN
    RAISE EXCEPTION 'Buyer budget receipt ACL or trigger differs';
  END IF;
END;
$postflight$;
