/* Copyright (C) 2023-2026 CinaGroup. SPDX-License-Identifier: AGPL-3.0-or-later */
const en = {
	catalogState: 'Catalog state',
	catalogState_missing: 'Missing',
	catalogState_empty: 'Empty catalog',
	catalogState_valid: 'Valid catalog',
	catalogState_invalid: 'Invalid catalog',
	catalogState_unsupported_fields:
		'Unsupported fields; original configuration preserved',
	activeState_configured: 'Explicit selection is configured',
	activeState_missing: 'No explicit selection; runtime fallback applies',
	activeState_invalid: 'Invalid explicit selection',
	activeState_ignored_without_catalog:
		'Explicit selection is ignored without a catalog',
	auditDetails: 'Audit details',
	auditActive: 'Explicit selection before → after',
	auditBeforeVersion: 'Version before',
	auditAfterVersion: 'Version after',
	aiBillingHelp:
		'Trimmed Unicode code points are billed as max(1, ceil(characters / billing unit)). The default 2,000-character billing unit is independent of upstream chunk length.',
	source_default: 'Default configuration',
	source_unavailable: 'Unavailable source',
	currency_configured: 'Configured currency',
	currency_missing: 'Legacy default USD; no currency row',
	currency_invalid: 'Invalid currency',
	currency_unsupported: 'Unsupported currency',
	recover: 'Review unknown operation',
	pending:
		'An earlier operation result is unknown. Changes and reveals remain locked across refreshes; do not repeat it.',
	unknownWrite:
		'The operation result is unknown. Its safety marker is retained.',
	confirmedLocked:
		'The operation was confirmed, but its safety marker could not be cleared. Manual review is required.',
	saved: 'The server confirmed this operation and its audit outcome.',
	auditOperation_save: 'Save configuration',
	auditOperation_save_activate: 'Save and activate',
	auditOperation_activate: 'Activate',
	auditOperation_legacy_save: 'Legacy save',
	auditOperation_reveal: 'Credential reveal',
	auditSource_admin_api: 'Admin API',
	auditSource_legacy_admin: 'Legacy admin',
	activationRequired:
		'Saving would change the effective engine or make it usable. Review and explicitly choose Save & activate.',
	activeCredentialRequired:
		'Clearing a required credential would make the effective engine unusable. Preserve it or review a valid engine switch.',
	lossRequired: 'Explicit loss-pricing acknowledgement is required.',
}
const zh: Record<keyof typeof en, string> = {
	catalogState: 'Catalog 状态',
	catalogState_missing: '缺失',
	catalogState_empty: '空 Catalog',
	catalogState_valid: '有效 Catalog',
	catalogState_invalid: '无效 Catalog',
	catalogState_unsupported_fields: '含不支持的字段，已保留原配置',
	activeState_configured: '已存显式选择',
	activeState_missing: '未存显式选择，使用运行时回退规则',
	activeState_invalid: '显式选择无效',
	activeState_ignored_without_catalog: '无 Catalog 时忽略显式选择',
	auditDetails: '审计详情',
	auditActive: '显式选择（变更前 → 后）',
	auditBeforeVersion: '变更前版本',
	auditAfterVersion: '变更后版本',
	aiBillingHelp:
		'去除首尾空白后的 Unicode 码点按 max(1, ceil(字符数 / 计费单元)) 计费。默认 2,000 字符计费单元独立于上游分块长度。',
	source_default: '默认配置',
	source_unavailable: '来源不可用',
	currency_configured: '已配置币种',
	currency_missing: '旧运行时默认 USD；未存币种行',
	currency_invalid: '币种无效',
	currency_unsupported: '不支持的币种',
	recover: '审阅未知操作',
	pending: '之前的操作结果未知。刷新后仍锁定修改和揭示，请勿重复操作。',
	unknownWrite: '操作结果未知，安全标记已保留。',
	confirmedLocked: '操作已确认，但安全标记未能清除，需要人工核对。',
	saved: '服务端已确认此操作及其审计结果。',
	auditOperation_save: '保存配置',
	auditOperation_save_activate: '保存并启用',
	auditOperation_activate: '启用',
	auditOperation_legacy_save: '旧页保存',
	auditOperation_reveal: '揭示凭据',
	auditSource_admin_api: '管理 API',
	auditSource_legacy_admin: '旧管理页',
	activationRequired:
		'保存将改变有效引擎或使其开始可用，请审阅并明确选择「保存并启用」。',
	activeCredentialRequired:
		'清除必需凭据将使有效引擎不可用，请保留凭据或审阅切换到其他可用引擎。',
	lossRequired: '必须明确确认亏损定价。',
}
const ja: Record<keyof typeof en, string> = {
	catalogState: 'Catalog の状態',
	catalogState_missing: '未設定',
	catalogState_empty: '空の Catalog',
	catalogState_valid: '有効な Catalog',
	catalogState_invalid: '無効な Catalog',
	catalogState_unsupported_fields: '未対応の項目あり・元の設定を保持',
	activeState_configured: '明示的な選択を保存済み',
	activeState_missing: '明示的な選択なし・ランタイムの代替規則を適用',
	activeState_invalid: '明示的な選択が無効',
	activeState_ignored_without_catalog: 'Catalog がないため明示的な選択を無視',
	auditDetails: '監査詳細',
	auditActive: '明示的な選択（変更前 → 後）',
	auditBeforeVersion: '変更前のバージョン',
	auditAfterVersion: '変更後のバージョン',
	aiBillingHelp:
		'前後の空白を除いた Unicode コードポイント数を max(1, ceil(文字数 / 課金単位)) で課金します。既定の 2,000 文字の課金単位は上流の分割長とは独立しています。',
	source_default: '既定の設定',
	source_unavailable: 'ソース利用不可',
	currency_configured: '設定済み通貨',
	currency_missing: '旧ランタイムの既定 USD・通貨行なし',
	currency_invalid: '無効な通貨',
	currency_unsupported: '未対応の通貨',
	recover: '結果不明の操作を確認',
	pending:
		'以前の操作結果は不明です。再読み込み後も変更と表示はロックされます。繰り返さないでください。',
	unknownWrite: '操作結果は不明です。安全マーカーを保持しています。',
	confirmedLocked:
		'操作は確認されましたが、安全マーカーを解除できません。手動確認が必要です。',
	saved: 'サーバーがこの操作と監査結果を確認しました。',
	auditOperation_save: '設定を保存',
	auditOperation_save_activate: '保存して有効化',
	auditOperation_activate: '有効化',
	auditOperation_legacy_save: '旧画面で保存',
	auditOperation_reveal: '認証情報の表示',
	auditSource_admin_api: '管理 API',
	auditSource_legacy_admin: '旧管理画面',
	activationRequired:
		'保存により有効なエンジンが変わるか利用可能になります。確認して「保存して有効化」を明示的に選択してください。',
	activeCredentialRequired:
		'必須認証情報を削除すると有効なエンジンが利用できなくなります。保持するか、利用可能な別エンジンへの切り替えを確認してください。',
	lossRequired: '損失価格の明示的な確認が必要です。',
}
const ko: Record<keyof typeof en, string> = {
	catalogState: 'Catalog 상태',
	catalogState_missing: '누락',
	catalogState_empty: '빈 Catalog',
	catalogState_valid: '유효한 Catalog',
	catalogState_invalid: '잘못된 Catalog',
	catalogState_unsupported_fields: '지원하지 않는 필드 · 원래 설정 유지',
	activeState_configured: '명시적 선택 저장됨',
	activeState_missing: '명시적 선택 없음 · 런타임 대체 규칙 적용',
	activeState_invalid: '잘못된 명시적 선택',
	activeState_ignored_without_catalog: 'Catalog 없이 명시적 선택 무시',
	auditDetails: '감사 세부 정보',
	auditActive: '명시적 선택(변경 전 → 후)',
	auditBeforeVersion: '변경 전 버전',
	auditAfterVersion: '변경 후 버전',
	aiBillingHelp:
		'앞뒤 공백을 제거한 Unicode 코드 포인트를 max(1, ceil(문자 수 / 과금 단위))로 과금합니다. 기본 2,000자 과금 단위는 업스트림 청크 길이와 별개입니다.',
	source_default: '기본 설정',
	source_unavailable: '소스 사용 불가',
	currency_configured: '설정된 통화',
	currency_missing: '기존 런타임 기본 USD · 통화 행 없음',
	currency_invalid: '잘못된 통화',
	currency_unsupported: '지원하지 않는 통화',
	recover: '결과를 모르는 작업 검토',
	pending:
		'이전 작업 결과를 알 수 없습니다. 새로고침 후에도 수정과 표시가 잠깁니다. 작업을 반복하지 마세요.',
	unknownWrite: '작업 결과를 알 수 없어 안전 마커를 유지합니다.',
	confirmedLocked:
		'작업은 확인됐지만 안전 마커를 지우지 못했습니다. 수동 확인이 필요합니다.',
	saved: '서버가 이 작업과 감사 결과를 확인했습니다.',
	auditOperation_save: '설정 저장',
	auditOperation_save_activate: '저장 후 활성화',
	auditOperation_activate: '활성화',
	auditOperation_legacy_save: '기존 화면 저장',
	auditOperation_reveal: '자격 증명 표시',
	auditSource_admin_api: '관리 API',
	auditSource_legacy_admin: '기존 관리 화면',
	activationRequired:
		'저장하면 실제 엔진이 바뀌거나 사용 가능해집니다. 검토 후 「저장 후 활성화」를 명시적으로 선택하세요.',
	activeCredentialRequired:
		'필수 자격 증명을 지우면 실제 엔진을 사용할 수 없습니다. 유지하거나 다른 사용 가능한 엔진으로 전환을 검토하세요.',
	lossRequired: '손실 가격을 명시적으로 확인해야 합니다.',
}
export const toolMessageExtras = { en, zh, ja, ko }
