/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=ChainWorkerEnv` (hash: 23902ef10a647fe23afb0bf124c16582)
interface __BaseEnv_ChainWorkerEnv {
	DB: D1Database;
	CINACHAIN_CHAIN_ID: "84532";
	CINACHAIN_RPC_URL: string;
	CINACHAIN_MINTER_PRIVATE_KEY: string;
	CINABADGE_CONTRACT_ADDRESS: string;
	CINACREDIT_CONTRACT_ADDRESS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ChainWorkerEnv {}
}
interface ChainWorkerEnv extends __BaseEnv_ChainWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CINACHAIN_CHAIN_ID" | "CINACHAIN_RPC_URL" | "CINACHAIN_MINTER_PRIVATE_KEY" | "CINABADGE_CONTRACT_ADDRESS" | "CINACREDIT_CONTRACT_ADDRESS">> {}
}
