/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/proxy/scripts/staging/wrangler.byok-d1-maintenance.jsonc --include-runtime=false --strict-vars=false --env-interface=ByokD1MaintenanceEnv packages/proxy/scripts/staging/byok-d1-maintenance-env.d.ts` (hash: 4fc4a9273dd5d9b842f6534feffd6ef3)
interface __BaseEnv_ByokD1MaintenanceEnv {
	RECOVERY_DB: D1Database;
	BYOK_MAINTENANCE_ENVIRONMENT: string;
	BYOK_MAINTENANCE_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./byok-d1-maintenance-worker");
	}
	interface Env extends __BaseEnv_ByokD1MaintenanceEnv {}
}
interface ByokD1MaintenanceEnv extends __BaseEnv_ByokD1MaintenanceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BYOK_MAINTENANCE_ENVIRONMENT" | "BYOK_MAINTENANCE_ENABLED">> {}
}

// Isolate generated bindings from other staging Worker globals.
export type { ByokD1MaintenanceEnv };
