/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/proxy/scripts/staging/wrangler.byok-d1-gateway.jsonc --include-runtime=false --strict-vars=false --env-interface=ByokD1GatewayEnv packages/proxy/scripts/staging/byok-d1-gateway-env.d.ts` (hash: 61838c2a4999bfe8e28056ef06542e26)
interface __BaseEnv_ByokD1GatewayEnv {
	BYOK_DB: D1Database;
	BYOK_GATEWAY_ENVIRONMENT: string;
	BYOK_GATEWAY_ENABLED: string;
	BYOK_GATEWAY_ACCESS_AUD: string;
	BYOK_GATEWAY_INSTALL_GRANT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./byok-d1-gateway-worker");
	}
	interface Env extends __BaseEnv_ByokD1GatewayEnv {}
}
interface ByokD1GatewayEnv extends __BaseEnv_ByokD1GatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BYOK_GATEWAY_ENVIRONMENT" | "BYOK_GATEWAY_ENABLED" | "BYOK_GATEWAY_ACCESS_AUD" | "BYOK_GATEWAY_INSTALL_GRANT">> {}
}

// Isolate generated bindings from other staging Worker globals.
export type { ByokD1GatewayEnv };
