/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/proxy/scripts/staging/wrangler.byok-d1-maintenance-control.jsonc --config=packages/proxy/scripts/staging/wrangler.byok-d1-maintenance.jsonc --include-runtime=false --strict-vars=false --env-interface=ByokD1MaintenanceControlEnv packages/proxy/scripts/staging/byok-d1-maintenance-control-env.d.ts` (hash: eb53013f734e3b078a5b55daf171acd7)
interface __BaseEnv_ByokD1MaintenanceControlEnv {
	BYOK_MAINTENANCE_CONTROL_ENVIRONMENT: string;
	BYOK_MAINTENANCE_CONTROL_ENABLED: string;
	BYOK_MAINTENANCE_ACCESS_AUD: string;
	USAGE_RECOVERY: Service<typeof import("./byok-d1-maintenance-worker").UsageRecovery>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./byok-d1-maintenance-control-worker");
	}
	interface Env extends __BaseEnv_ByokD1MaintenanceControlEnv {}
}
interface ByokD1MaintenanceControlEnv extends __BaseEnv_ByokD1MaintenanceControlEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BYOK_MAINTENANCE_CONTROL_ENVIRONMENT" | "BYOK_MAINTENANCE_CONTROL_ENABLED" | "BYOK_MAINTENANCE_ACCESS_AUD">> {}
}

// Isolate generated bindings from other staging Worker globals.
export type { ByokD1MaintenanceControlEnv };
