/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/staging/wrangler.chat-holder-gateway-v364.jsonc --include-runtime=false --strict-vars=false --env-interface=ChatHolderGatewayV364Env scripts/staging/chat-holder-gateway-v364-env.d.ts` (hash: 340525310ba59a6b7d7711af95c99c58)
interface __BaseEnv_ChatHolderGatewayV364Env {
	TEXT_HOLDER: Fetcher /* cinatoken-staging-chat-holder-private-fixture-v364 */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./chat-holder-gateway-v364");
	}
	interface Env extends __BaseEnv_ChatHolderGatewayV364Env {}
}
interface ChatHolderGatewayV364Env extends __BaseEnv_ChatHolderGatewayV364Env {}
