/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/staging/wrangler.chat-holder-private-v364.jsonc --include-runtime=false --strict-vars=false --env-interface=ChatHolderPrivateV364Env scripts/staging/chat-holder-private-v364-env.d.ts` (hash: 065343ca21ef5c755ac5e255432ccb53)
interface __BaseEnv_ChatHolderPrivateV364Env {
	OBSERVATIONS: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./chat-holder-private-v364");
	}
	interface Env extends __BaseEnv_ChatHolderPrivateV364Env {}
}
interface ChatHolderPrivateV364Env extends __BaseEnv_ChatHolderPrivateV364Env {}
