/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.wrangler/staging/images-proxy/wrangler.jsonc --include-runtime=false --env-interface=ImagesStagingEnv packages/proxy/scripts/staging/images-env.d.ts` (hash: 59570dc6601305c4d20adc7fbd78408e)
interface __BaseEnv_ImagesStagingEnv {
	DB: D1Database;
	AUTH_RATE_LIMITER: RateLimit;
	PUBLIC_STATS_RATE_LIMITER: RateLimit;
	ANALYTICS_RATE_LIMITER: RateLimit;
	DATABASE_DRIVER: "d1";
	REQUEST_BODY_LOGGING: "off";
	BATCH_API_ENABLED: "false";
	SHARED_KEY_ENCRYPTION_SECRET: string;
	IMAGE_UPSTREAM: Fetcher /* cinatoken-staging-images-upstream */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./images-gateway");
	}
	interface Env extends __BaseEnv_ImagesStagingEnv {}
}
interface ImagesStagingEnv extends __BaseEnv_ImagesStagingEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_DRIVER" | "REQUEST_BODY_LOGGING" | "BATCH_API_ENABLED" | "SHARED_KEY_ENCRYPTION_SECRET">> {}
}
