/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/proxy/scripts/staging/wrangler.images-upstream.jsonc --include-runtime=false --env-interface=ImagesUpstreamEnv packages/proxy/scripts/staging/images-upstream-env.d.ts` (hash: 3676ad16d0804aa35f5346c602358da3)
interface __BaseEnv_ImagesUpstreamEnv {
	PROBE_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./images-upstream");
	}
	interface Env extends __BaseEnv_ImagesUpstreamEnv {}
}
interface ImagesUpstreamEnv extends __BaseEnv_ImagesUpstreamEnv {}
