/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/staging/wrangler.usage-recovery-control.jsonc --config=scripts/staging/wrangler.usage-recovery.jsonc --include-runtime=false --strict-vars=false --env-interface=UsageRecoveryControlEnv scripts/staging/usage-recovery-control-env.d.ts` (hash: 7ecd47df1047d4a659c56ce2943ee941)
interface __BaseEnv_UsageRecoveryControlEnv {
	RECOVERY_CONTROL_ENVIRONMENT: string;
	RECOVERY_CONTROL_ENABLED: string;
	RECOVERY_CONTROL_ACCESS_AUD: string;
	USAGE_RECOVERY: Service<typeof import("./usage-recovery-worker").UsageRecovery>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./usage-recovery-control-worker");
	}
	interface Env extends __BaseEnv_UsageRecoveryControlEnv {}
}
interface UsageRecoveryControlEnv extends __BaseEnv_UsageRecoveryControlEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RECOVERY_CONTROL_ENVIRONMENT" | "RECOVERY_CONTROL_ENABLED" | "RECOVERY_CONTROL_ACCESS_AUD">> {}
}

// Module scope prevents this Worker from merging Env/GlobalProps with the receiver.
export type { UsageRecoveryControlEnv };
