/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/proxy/scripts/staging/wrangler.usage-recovery.jsonc --include-runtime=false --strict-vars=false --env-interface=UsageRecoveryWorkerEnv packages/proxy/scripts/staging/usage-recovery-env.d.ts` (hash: dc121c19ba1a4240fa6ab3e4db74c0b7)
interface __BaseEnv_UsageRecoveryWorkerEnv {
	RECOVERY_DB: D1Database;
	RECOVERY_ENVIRONMENT: string;
	RECOVERY_ENABLED: string;
	RECOVERY_MAX_ITEMS: string;
	RECOVERY_CONCURRENCY: string;
	RECOVERY_LEASE_SECONDS: string;
	RECOVERY_RUN_BUDGET_MS: string;
	RECOVERY_RESERVED_BYTES: string;
	RECOVERY_INSTANCE_BYTES: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./usage-recovery-worker");
	}
	interface Env extends __BaseEnv_UsageRecoveryWorkerEnv {}
}
interface UsageRecoveryWorkerEnv extends __BaseEnv_UsageRecoveryWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RECOVERY_ENVIRONMENT" | "RECOVERY_ENABLED" | "RECOVERY_MAX_ITEMS" | "RECOVERY_CONCURRENCY" | "RECOVERY_LEASE_SECONDS" | "RECOVERY_RUN_BUDGET_MS" | "RECOVERY_RESERVED_BYTES" | "RECOVERY_INSTANCE_BYTES">> {}
}
