/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.complete-text-response-holder-v394.jsonc --include-runtime=false --strict-vars=false --env-interface=CompleteTextResponseHolderV394Env src/runtime/complete-text-response-holder-v394-env.d.ts` (hash: a1ad189ab59bdb00a72644e9a1244d2c)
interface __BaseEnv_CompleteTextResponseHolderV394Env {
	COMPLETE_TEXT_READER: Hyperdrive;
	COMPLETE_TEXT_GRANTER: Hyperdrive;
	COMPLETE_TEXT_HOLDER: Hyperdrive;
	COMPLETE_TEXT_RENEWER: Hyperdrive;
	COMPLETE_TEXT_HOLDER_ENABLED: string;
	PROVIDER_KEY_ENCRYPTION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./complete-text-response-holder-worker-v394");
	}
	interface Env extends __BaseEnv_CompleteTextResponseHolderV394Env {}
}
interface CompleteTextResponseHolderV394Env extends __BaseEnv_CompleteTextResponseHolderV394Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COMPLETE_TEXT_HOLDER_ENABLED" | "PROVIDER_KEY_ENCRYPTION_SECRET">> {}
}
