/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.complete-text-holder-v390.jsonc --include-runtime=false --strict-vars=false --env-interface=CompleteTextHolderV390Env src/runtime/complete-text-holder-v390-env.d.ts` (hash: 06f797d99977313cd3c8ae86300c8ae7)
interface __BaseEnv_CompleteTextHolderV390Env {
	COMPLETE_TEXT_READER: Hyperdrive;
	COMPLETE_TEXT_GRANTER: Hyperdrive;
	COMPLETE_TEXT_HOLDER: Hyperdrive;
	COMPLETE_TEXT_RENEWER: Hyperdrive;
	COMPLETE_TEXT_HOLDER_ENABLED: string;
	PROVIDER_KEY_ENCRYPTION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./complete-text-holder-worker-v390");
	}
	interface Env extends __BaseEnv_CompleteTextHolderV390Env {}
}
interface CompleteTextHolderV390Env extends __BaseEnv_CompleteTextHolderV390Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COMPLETE_TEXT_HOLDER_ENABLED" | "PROVIDER_KEY_ENCRYPTION_SECRET">> {}
}

// Scope this Worker-only binding contract to its module, including Wrangler's
// NodeJS.ProcessEnv projection; it must not alter unrelated Node scripts.
import type { Hyperdrive } from '@cloudflare/workers-types';
export type { CompleteTextHolderV390Env };
