/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.complete-text-no-fetch-recovery-v389.jsonc --include-runtime=false --strict-vars=false --env-interface=CompleteTextNoFetchRecoveryV389Env src/runtime/complete-text-no-fetch-recovery-v389-env.d.ts` (hash: c645b41b73936b40a450191f01bf2ed9)
interface __BaseEnv_CompleteTextNoFetchRecoveryV389Env {
	COMPLETE_TEXT_RECOVERY_WORKER: Hyperdrive;
	COMPLETE_TEXT_RECOVERY_OBSERVER: Hyperdrive;
	COMPLETE_TEXT_NO_FETCH_RESOLVER: Hyperdrive;
	COMPLETE_TEXT_PLATFORM_CLOSER: Hyperdrive;
	COMPLETE_TEXT_NO_FETCH_RECOVERY_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./complete-text-no-fetch-recovery-worker-v389");
	}
	interface Env extends __BaseEnv_CompleteTextNoFetchRecoveryV389Env {}
}
interface CompleteTextNoFetchRecoveryV389Env extends __BaseEnv_CompleteTextNoFetchRecoveryV389Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COMPLETE_TEXT_NO_FETCH_RECOVERY_ENABLED">> {}
}
